// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhoR-A_dQEJTRRxQ36pCQ_SKZgKtlk2CY',
    appId: '1:746937972189:web:a14c9212cd41d5d2347234',
    messagingSenderId: '746937972189',
    projectId: 'twitter-dev-7a99c',
    authDomain: 'twitter-dev-7a99c.firebaseapp.com',
    storageBucket: 'twitter-dev-7a99c.appspot.com',
    measurementId: 'G-8N7EGVDXXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJb73oS--2hvTbf0iZH4Ty7MsoGyKOdU',
    appId: '1:746937972189:android:7f6cf55dadeb6f03347234',
    messagingSenderId: '746937972189',
    projectId: 'twitter-dev-7a99c',
    storageBucket: 'twitter-dev-7a99c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0hh-LZtijCIzfeSzYaXu2DfSd-xbpkgI',
    appId: '1:746937972189:ios:64695585824e85be347234',
    messagingSenderId: '746937972189',
    projectId: 'twitter-dev-7a99c',
    storageBucket: 'twitter-dev-7a99c.appspot.com',
    iosBundleId: 'com.example.flutterTwitter',
  );
}
